project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!*.Rmd"
  resources:
    - "slides/*.pdf"
    - "slides/*.html"

website:
  page-navigation: true
  repo-url: "https://github.com/selinaZitrone/get-started-with-git"
  site-url: "https://selinazitrone.github.io/get-started-with-git/"
  repo-actions: [edit, issue]
  repo-branch: master
  title: "Git course"

  navbar:
    right:
      - text: Sessions
        menu:
          - text: 01 - Introduction to Git
            href: sessions/01_intro_git.qmd
          - text: 02 - Collaboration with Git
            href: sessions/02_git_collaboration.qmd
      - text: How-to-guides
        menu: 
          - text: GitHub Desktop
            href: how-tos/git_workflow_gh_desktop.qmd
          - text: Terminal
            href: how-tos/git_workflow_terminal.qmd
          - text: RStudio, R and `usethis`
            href: how-tos/git_workflow_usethis.qmd
          - text: VS Code
            href: how-tos/git_workflow_vscode.qmd
          - text: Create pull requests on GitHub
            href: how-tos/create_pull_request.qmd
          - text: Utility - Set up SSH keys
            href: how-tos/ssh_keys.qmd
      - text: Resources
        href: resources.qmd
      - icon: github
        href: https://github.com/selinaZitrone/get-started-with-git
    left: 
      - text: Course preparation
        href: course_preparation.qmd


format:
  html:
    embed-resources: true
    theme:
      light: [flatly, style/theme_light.scss]
      dark: [darkly, style/theme_dark.scss]
    css: style/style.css
    toc: true
    code-copy: true
    code-overflow: wrap



