---
title: "Course preparations"
---

In order to have a smooth workshop start, you need to prepare a few technical things
so you can jump right into using Git on the first day.

# Install Git on your machine

You can follow my guide below but you can also find the download and installation guides for all major operating systems
[on the official Git website](https://git-scm.com/downloads).
If you have an old version of Git already installed, please make sure to update it
prior to the workshop. You can checkout [this article](https://www.howtogeek.com/759319/how-to-check-and-update-your-git-version/)
that explains how to find your current Git version and how to update to a newer one.

:::{.panel-tabset}

# Windows

You can download Git from [here](https://git-scm.com/download/win).

Download and install the correct version for your machine (just click "Click here to download"). Use recommended or default settings during the installation. Most options can also be changed later if you want to.

With the Git installation for Windows, you also get a program called "Git Bash". 
Git Bash is a terminal application for Windows that provides a Git command line experience.

Open the Git Bash application (you can find it searching in the Windows search bar) 
and run (just type it and hit Enter)

```sh
git --version
```

If the Git installation was successful, you should see the version of Git printed to the console.

# Linux (Ubuntu)

You can install Git from the terminal. Run

```sh
sudo apt-get update
sudo apt-get install git
```

Check the version of Git that you have installed with

```sh
git --version
```

# MacOS

If you are using Xcode, you might already have Git installed. To check if this is the case, open the terminal and run

```sh
git --version
```

If the terminal tells you which version of Git is installed, you can check if you can update your current Git installation.

If you need to install Git, you can do this with homebrew. Just run

```sh
brew install git
```

Then check the version and verify the installation with 

```sh
git --version
```

:::

# Sign up for GitHub

I will use GitHub as a remote repository service in the workshop and you can [create an account here](https://github.com/join). 

::: {.callout-tip}

## Use your institutional email address to get benefits

If you sign up for GitHub with an institutional email address, you can get a free upgrade to GitHub Pro.
This gives you some additional benefits like private wikis and more. You can always add a second email address later or change it if you leave your institution.

:::

# Install GitHub Desktop

In the course, I'll be using the GitHub Desktop application as a graphical user
interface to work with Git.

There are detailed step by step guides on how to install and set up GitHub Desktop
on the GitHub Website. Please follow [this guide](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/installing-and-authenticating-to-github-desktop/setting-up-github-desktop#part-1-installing-github-desktop) and 
do Part 1 (Installing GitHub Desktop) and Part 2 (Configuring your account).

:::{.callout-note}

## Linux users

If you are running a Linux OS, you can install GitHub Desktop from the [shiftkey repository](https://github.com/shiftkey/desktop) as
on the GitHub Desktop website, there is only a Windows and MacOS version available.
When you are done with the installation step, please head over to the GitHub Desktop documentation linked
above and follow Part 2 (Configuring your account).

:::

