---
title: "Introduction to version control with git"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

# Workshop organization and schedule

# Workshop Material

You can find all the workshop material on this website.
On top, you can navigate to the presentation slides and the tasks.

To download presentation slides in pdf format, you can use the following links:

<!-- - <a href="./slides/01_01_RStudio.pdf" download> 01 - Introduction RStudio</a> -->

# Prerequisites

To follow everything we discuss in the workshop you need to prepare a few things:

## 1. Install git on your machine

If you don't have git installed already, follow the instructions below to install git for your OS.

**For Windows**

You can download git from [here](https://git-scm.com/download/win)

Download and install the correct version for your machine (probably 64 bit).

With the git installation for windows, you should also get a program called `Git bash`. 
Git bash is a linux like command line for Windows.

When you are done, open this program (you can find it after searching for it in the Windows search bar) 
and run `git --version`. If you successfully installed git, you should see the version
of git that you are using printed to the console.

**For Linux (Ubuntu/Debian)**

You can install git in the terminal. Run

```
sudo apt-get update
sudo apt-get install git
```

Check the version of git that you have installed with

```
git --version
```

**For MacOS**

Some versions of MacOS come with git preinstalled. To check if you already have it, open the terminal and run

```
git --version
```

If the terminal tells you which verison of git is installed, you can skip the next steps.

If you need to install git, you can do this with homebrew. Just run

```
brew install git
```

Then check the version and verify the installation with 

```
git --versions
```

## Github/Gitlab account

If you don't have a Gitlab or Github account yet, you can make one to follow the tutorials in the workshop.
I will use Github in the examples that I will show you, but Gitlab will work as well.

If you don't have any Account for a remote repository hoster, I suggest to [make a Github account](https://github.com/join).

Tip: If you do your Github account with an institutional email address, you will get a free upgrade to Github Pro.
This gives you some benefits like private wikis, ... You can always add a second email address later or change it if you leave your institution.

## SSH Authentication

In order to communicate between your local machine and your Github/Gitlab account,
you need to set up authentication via SSH keys.
Please follow the instructions <a href="./tasks/ssh_keys_how.html"> here</a> to do so.


