---
title: Git resources for learning
from: markdown+emoji
---

## Learn Git

- [Learn git concepts, not commands](https://dev.to/unseenwizzard/learn-git-concepts-not-commands-4gjc): Very nice blogpost. Explains the concepts of git really well, also more advanced ones like `rebase` or `cherry-pick`.
  - Is related to [this Git training](https://github.com/UnseenWizzard/git_training) for learning the Git
concepts in the command line. 

- [How to write good commit messages](https://cbea.ms/git-commit/): Explains why good commit messages are important and gives 7 rules for writing them.

- [Git book](https://git-scm.com/book/en/v2): Explains git concepts from the very beginning.

### Git :heart: command line

- [Git cheat sheet](https://education.github.com/git-cheat-sheet-education.pdf): Always handy if you don't remember the basic commands for the 
terminal.

### Git :heart: R

- There is a whole [book on using Git with R](https://happygitwithr.com/) that 
explains the setup in detail but also goes into more advanced topics.

- Follow this [step by step guide](https://rfortherestofus.com/2021/02/how-to-use-git-github-with-r/)
to set up Git and a GitHub connection in R and R Studio

### Git :heart: GitHub Desktop

- There are detailed step by step guides on how to set up GitHub Desktop and how to
work with in the [GitHub Desktop Documentation](https://docs.github.com/desktop)

### Git :heart: VS Code

- The [VS Code documentation](https://code.visualstudio.com/docs/sourcecontrol/intro-to-git) has a nice section on version control with Git in VS Code.
- For uses specifically with GitHub, also have a look at the [GitHub in VS Code documentation](https://code.visualstudio.com/docs/sourcecontrol/github).

## Other useful things

- [Connect GitHub Desktop with a Gitlab repository](https://itnext.io/how-to-use-github-desktop-with-gitlab-cd4d2de3d104?gi=b32bd84e7fe4): This is interesting if you want to use GitHub Desktop but your repository is on GitLab (e.g. because your institution has it's own GitLab server).
- [Connecting the repo with Zenodo to get a DOI](https://emilio-berti.github.io/idiv-git-introduction/21-github_zenodo/index.html): Important if you want to make your code citable, especially if it's connected to a publication.
- [A markdown cheat sheet for your README files](https://github.com/im-luka/markdown-cheatsheet): READMES are essential for good repositories. Check out the markdown cheat sheet for formatting options.